---
language: cpp
cache: ccache
sudo: false
addons:
  apt:
    sources: george-edison55-precise-backports
    packages:
    - doxygen
    - graphviz
    - libasound2-dev
    - g++-multilib
    - rpm
env:
  global:
  - secure: DE9IUM+pIV757GU0ccfDJhA752442pKu3DyBthrzHW9+GbsqbfuJOx045CYNN5vOWutFPC0A51B9WxhLNpXXqD3mfU8MhP1gkF7SskrHvcAPrCyfdqZf1Q8XDP5phm2KbHhhwxQMYmmicd6yj8DPNy2wRoSgPSDp/ZUDk51XZDU=
  - secure: AfoHc5tpnYoI2TVGUeE9Xdru+15pd5N4YzO7EWvwmMnrHtNO3retrmKOGpnIyfbP2BeWRTW/z+BI4G0RrfvubjHu2us4wRh6Jq8+UZohBBkM+ldTnyqYHX97q+6ScWBWZGg7dpthd1x/7fmds8dSRzustHUhI7RzPbWEMQH1DGI=
  - NUMJOBS=4
  - RPI=1
  - USE_CCACHE=1
  - CCACHE_SLOPPINESS=pch_defines,time_macros
  - CCACHE_COMPRESS=1
matrix:
  fast_finish: true
  include:
  - compiler: gcc-armeabi-v6-static
    env: URHO3D_LIB_TYPE=STATIC
  - compiler: gcc-armeabi-v6-shared
    env: URHO3D_LIB_TYPE=SHARED
  - compiler: gcc-armeabi-v7a-static
    env: URHO3D_LIB_TYPE=STATIC RPI_ABI=armeabi-v7a
  - compiler: gcc-armeabi-v7a-shared
    env: URHO3D_LIB_TYPE=SHARED RPI_ABI=armeabi-v7a
before_script:
- git clone --depth 1 https://github.com/raspberrypi/tools.git rpi-tools && export
  RPI_PREFIX=$(pwd)/rpi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf
  && git clone --depth 1 --branch strip https://github.com/urho3d/rpi-sysroot.git
  && export RPI_SYSROOT=$(pwd)/rpi-sysroot && for f in $RPI_PREFIX-{gcc,g++}; do touch
  -d "2015-01-01 00:00:00 +0800" $f; done
- export TRAVIS_COMMIT=$TRAVIS_COMMIT~
- export TAG=$(git describe --exact-match $TRAVIS_COMMIT 2>/dev/null); if [[ $TAG
  =~ [[:digit:]]+\.[[:digit:]]+ ]]; then export RELEASE_TAG=$TAG; fi
- export COMMIT_MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- if [ $RELEASE_TAG ] || (! [[ $TRAVIS_BRANCH =~ [^-]+-[^-]+-CI ]] && echo $COMMIT_MESSAGE
  |grep -cq '\[ci package\]'); then export PACKAGE_UPLOAD=1; fi
- export PATH=$(whereis -b ccache |grep -o '\S*lib\S*'):${RPI_PREFIX%/*}:$PATH
- ccache -z -M 100M
script: rake ci
before_cache: ccache -s
after_success: if [ $PACKAGE_UPLOAD ]; then rake ci_package_upload; fi
after_script: if [ ${TRAVIS_JOB_NUMBER##*.} == 4 ]; then rake ci_delete_mirror; fi
